version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    groups:
      production:
        patterns:
          - "*"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development:
        patterns:
          - "*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    reviewers:
      - "XiSenao"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/packages/vitepress"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "XiSenao"
