packages:
  - 'packages/*'
  - 'packages/*/docs'
  - 'packages/*/playground'
  - 'packages/plugins/*'
  - 'docs'
  - 'utils'
  - '!**/dist'

onlyBuiltDependencies:
  - esbuild
  - '@swc/core'
  - playwright-chromium

# "Vite isn't updating esbuild to 0.25.0 in v5, and since the project doesn't use esbuild dev server, this can be ignored."
auditConfig:
  ignoreGhsas:
    - GHSA-67mh-4wv8-2f99

overrides:
  axios@<1.12.0: '>=1.12.0'
  # @vitejs/plugin-react-swc depends on @swc/core.
  # Since @swc/core@1.13.21 is broken, the version is temporarily locked to v1.13.5.
  # https://github.com/swc-project/swc/issues/11129
  '@swc/core': '1.13.5'
  '@types/node': '^22.19.0'

nodeVersion: 20.19.0

engineStrict: true

patchedDependencies:
  vite: patches/vite@5.4.21.patch

autoInstallPeers: false

dedupeInjectedDeps: false

hoist: false

loglevel: info

shellEmulator: true

strictPeerDependencies: true

catalogs:
  # Linting tools (centralized in @docs-islands/eslint-config)
  lint:
    '@eslint/js': '^9.34.0'
    'eslint': '^9.34.0'
    'eslint-config-prettier': '^10.1.8'
    'eslint-plugin-regexp': '^2.1.0'
    'eslint-plugin-jsx-a11y': '^6.10.2'
    'eslint-plugin-prettier': '^5.5.4'
    'eslint-plugin-react': '^7.37.2'
    'eslint-plugin-react-hooks': '^7.0.1'
    'eslint-plugin-n': '^17.23.1'
    'eslint-plugin-unicorn': '^62.0.0'
    'eslint-plugin-vue': '^10.4.0'
    'eslint-plugin-pnpm': '^1.3.0'
    '@html-eslint/eslint-plugin': '^0.47.0'
    '@html-eslint/parser': '^0.47.0'
    '@eslint/markdown': '^7.4.0'
    'vue-eslint-parser': '^10.2.0'
    '@typescript-eslint/parser': '^8.42.0'
    'jsonc-eslint-parser': '^2.4.1'
    'yaml-eslint-parser': '^1.3.0'
    'typescript-eslint': '^8.40.0'
    'publint': '^0.3.14'

  format:
    'prettier': '~3.5.3'
    'prettier-plugin-organize-imports': '^4.2.0'

  dev:
    'husky': '^9.1.7'
    'lint-staged': '^16.1.5'
    'typescript': '~5.9.3'
    'vue-tsc': '~3.1.2'
    '@types/babel__generator': '^7.27.0'
    '@types/babel__traverse': '^7.20.7'
    '@types/estree': '^1.0.8'
    '@types/markdown-it': '^14.1.2'
    '@types/eslint-plugin-jsx-a11y': '^6.10.1'
    '@types/node': '^22.19.0'
    '@types/react': '^18.2.0'
    '@types/react-dom': '^18.2.0'
    'del-cli': '^7.0.0'
    'tsx': '^4.20.5'
    'wait-on': '^9.0.1'
    'react': '^18.2.0'
    'react-dom': '^18.2.0'
    'es-module-lexer': '^1.7.0'
    'magic-string': '^0.30.17'
    'markdown-it': '^14.1.0'
    'parse5': '^8.0.0'
    'pathe': '^2.0.3'
    'picocolors': '1.1.1'
    '@babel/generator': '^7.28.0'
    '@babel/parser': '^7.28.0'
    '@babel/traverse': '^7.28.0'
    '@babel/types': '^7.28.2'
    'rolldown': '1.0.0-beta.31'
    'rolldown-plugin-dts': '^0.17.2'
    'rollup-plugin-license': '^3.6.0'
    '@vitejs/plugin-react-swc': '^4.2.0'
    'concurrently': '^9.2.1'

  prod:
    'vite': '^5.4.21'
    'tinyglobby': '^0.2.15'
    'cheerio': '^1.1.0'
    'vue': '^3.5.21'

  # Documentation-specific development dependencies
  docs-dev:
    '@types/http-proxy': '^1.17.16'
    '@nolebase/vitepress-plugin-enhanced-mark': '^2.18.2'
    'vitepress-plugin-group-icons': '^1.6.3'
    'vitepress-plugin-llms': '^1.7.3'
    'http-proxy': '^1.18.1'

  # Integrated Framework versions (shared across docs)
  frameworks:
    'vitepress': '^1.6.4'

  test:
    'playwright-chromium': '1.56.1'
    '@playwright/test': '1.56.1'
    'get-port': '^7.1.0'
    'globals': '^16.4.0'
    'jsdom': '^25.0.0'
    'vitest': '3.2.4'
