packages:
  - 'packages/**'
  - 'docs'
  - 'utils'
  - '!**/dist'

onlyBuiltDependencies:
  - esbuild
  - '@swc/core'
  - playwright-chromium

autoInstallPeers: false

dedupeInjectedDeps: false

hoist: false

loglevel: info

patchedDependencies:
  vite: patches/vite@5.4.20.patch

shellEmulator: true

strictPeerDependencies: true
