export const VITEPRESS_LOG_GROUPS = {
  buildFrameworkBrowserBundle: 'build.framework.bundle.browser',
  buildFrameworkMpaIntegration: 'build.framework.mpa-integration',
  buildFrameworkSsrBundle: 'build.framework.bundle.ssr',
  buildFrameworkBuildFinalize: 'build.framework-build.finalize',
  buildFrameworkBuildSsrIntegration: 'build.framework-build.ssr-integration',
  buildFrameworkBuildTransformHtml: 'build.framework-build.transform-html',
  buildSharedClientRuntimeMetafile: 'build.shared-client-runtime.metafile',
  configNodeVersion: 'config.node-version',
  hmrMarkdownUpdate: 'plugin.hmr.markdown-update',
  hmrReactSsrOnlyRender: 'hmr.react.ssr-only-render',
  hmrViteAfterUpdate: 'hmr.vite.after-update',
  hmrViteAfterUpdateRender: 'hmr.vite.after-update.render',
  parserFramework: 'parser.framework',
  parserReact: 'parser.react',
  pluginRenderingStrategies: 'plugin.rendering-strategies',
  resolverInlinePage: 'resolver.vitepress.inline-page',
  runtimeReactClientLoader: 'runtime.react.client-loader',
  runtimeReactComponentManager: 'runtime.react.component-manager',
  runtimeReactDevRender: 'runtime.react.dev-render',
  runtimeReactDevRuntimeLoader: 'runtime.react.dev-runtime-loader',
  runtimeCssLoading: 'runtime.css.loading',
  siteDevtoolsAiBuildReports: 'site-devtools.ai.build-reports',
  siteDevtoolsAiServer: 'site-devtools.ai.server',
} as const;
