name: "Setup Environment"
description: "Setup Node.js, pnpm and dependencies with caching"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "22"
  playwright:
    description: "Install Playwright browsers"
    required: false
    default: "false"
  frozen-lockfile:
    description: "Use frozen lockfile"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      # pnpm/action-setup@v4.2.0.
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
      with:
        run_install: false

    - name: Setup Node.js and cache pnpm store
      # actions/setup-node@v5.0.0.
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: |
        # Use frozen-lockfile by default unless explicitly set to false
        if [[ "${{ inputs.frozen-lockfile }}" == "false" ]]; then
          echo "Installing dependencies without frozen lockfile..."
          pnpm install --no-frozen-lockfile
        else
          echo "Installing dependencies with frozen lockfile..."
          pnpm install --frozen-lockfile
        fi

    # Install playwright's binary under custom directory to cache
    - name: (non-windows) Set Playwright path and Get playwright version
      if: inputs.playwright == 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/.cache/playwright-bin" >> $GITHUB_ENV
        PLAYWRIGHT_VERSION="$(pnpm ls --depth 0 --json -w playwright-chromium | jq --raw-output '.[0].devDependencies["playwright-chromium"].version')"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

    - name: (windows) Set Playwright path and Get playwright version
      if: inputs.playwright == 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "PLAYWRIGHT_BROWSERS_PATH=$HOME\.cache\playwright-bin" >> $env:GITHUB_ENV
        $env:PLAYWRIGHT_VERSION="$(pnpm ls --depth 0 --json -w playwright-chromium | jq --raw-output '.[0].devDependencies["playwright-chromium"].version')"
        echo "PLAYWRIGHT_VERSION=$env:PLAYWRIGHT_VERSION" >> $env:GITHUB_ENV

    - name: Cache Playwright's binary
      if: inputs.playwright == 'true'
      # actions/cache@v4.3.0.
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        key: ${{ runner.os }}-playwright-bin-v1-${{ env.PLAYWRIGHT_VERSION }}
        path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
        restore-keys: |
          ${{ runner.os }}-playwright-bin-v1-

    - name: Install Playwright
      if: inputs.playwright == 'true'
      shell: bash
      # does not need to explicitly set chromium after https://github.com/microsoft/playwright/issues/14862 is solved
      run: pnpm playwright install chromium
