import type { Writable } from 'node:stream';
import { fileURLToPath } from 'node:url';
import type {
  SiteDebugBuildArtifactSnapshot,
  SiteDebugBuildComponentSummary,
  SiteDebugBuildDataOptions,
  SiteDebugBuildOverview,
  SiteDebugBuildPageSummary,
  SiteDebugBuildReportPayload,
} from './react/site-debug-build-data';
import { SiteDebugBuildDataStore } from './react/site-debug-build-data';

type JsonRpcId = number | string | null;

interface JsonRpcRequest {
  id?: JsonRpcId;
  jsonrpc?: string;
  method: string;
  params?: unknown;
}

interface JsonRpcResponse {
  error?: {
    code: number;
    message: string;
  };
  id: JsonRpcId;
  jsonrpc: '2.0';
  result?: unknown;
}

export type SiteDebugBuildMcpToolName =
  | 'get_artifact'
  | 'get_build_overview'
  | 'get_build_report'
  | 'get_component'
  | 'get_page'
  | 'list_pages';

export interface SiteDebugBuildMcpServerOptions
  extends SiteDebugBuildDataOptions {
  stderr?: Writable;
  stdin?: NodeJS.ReadableStream;
  stdout?: Writable;
}

type SiteDebugBuildMcpToolResult =
  | SiteDebugBuildArtifactSnapshot
  | SiteDebugBuildComponentSummary
  | {
      error: string;
    }
  | SiteDebugBuildOverview
  | SiteDebugBuildPageSummary[]
  | SiteDebugBuildReportPayload
  | {
      page: unknown;
      summary: SiteDebugBuildPageSummary;
    };

interface SiteDebugBuildMcpResource {
  description: string;
  mimeType: 'text/markdown';
  name: string;
  text: string;
  uri: string;
}

const SERVER_NAME = 'docs-islands-site-debug-build-mcp';
const SERVER_VERSION = '1.0.0';
const PROTOCOL_VERSION = '2024-11-05';
const HELP_TEXT = `
Usage:
  docs-islands-vitepress-site-debug-mcp --outDir <path> [--assetsDir <dir>]

Options:
  --outDir     Built docs output directory. Required.
  --assetsDir  Assets directory name inside outDir. Defaults to "assets".
  --help       Show this message.
`.trim();

const MCP_RESOURCES: SiteDebugBuildMcpResource[] = [
  {
    description:
      'Overview of the build-time data exposed by the Site Debug MCP server.',
    mimeType: 'text/markdown',
    name: 'site-debug-build-data-overview',
    text: [
      '# Site Debug Build Data Overview',
      '',
      'This MCP server exposes build-time data generated by docs-islands site debug instrumentation.',
      '',
      'Available data:',
      '- Page metafile manifest',
      '- Per-page page metafile JSON payloads',
      '- Component build metrics',
      '- Artifact snapshots shaped like the shared AI prompt context',
      '- Build-time AI report JSON payloads',
      '',
      'This server does not read browser runtime state and does not invoke AI providers.',
    ].join('\n'),
    uri: 'file://docs-islands/site-debug-build-data-overview.md',
  },
  {
    description:
      'Recommended tool usage flow for exploring docs-islands build artifacts.',
    mimeType: 'text/markdown',
    name: 'site-debug-build-tool-guide',
    text: [
      '# Site Debug Build Tool Guide',
      '',
      'Recommended exploration flow:',
      '1. Call `get_build_overview` to confirm the loaded build.',
      '2. Call `list_pages` to find available page IDs.',
      '3. Call `get_page` for a specific page.',
      '4. Call `get_component` for a component on that page.',
      '5. Call `get_artifact` for a chunk or module artifact snapshot.',
      '6. Call `get_build_report` to inspect a saved AI report payload when needed.',
      '',
      'Stable identifiers:',
      '- Pages use `pageId`.',
      '- Components use `pageId + componentName`.',
      '- Chunk artifacts use `artifactKind + displayPath`.',
      '- Module artifacts use `artifactKind + displayPath` or `file + moduleId`.',
      '- Build reports use `reportId` or `artifactKey`.',
    ].join('\n'),
    uri: 'file://docs-islands/site-debug-build-tool-guide.md',
  },
];

const MCP_TOOLS = [
  {
    description:
      'Return build ID, page count, component count, total bundle bytes, and whether AI reports exist.',
    inputSchema: {
      additionalProperties: false,
      properties: {},
      type: 'object',
    },
    name: 'get_build_overview',
  },
  {
    description:
      'List all page IDs with their page metafile references and summary metadata.',
    inputSchema: {
      additionalProperties: false,
      properties: {},
      type: 'object',
    },
    name: 'list_pages',
  },
  {
    description:
      'Return the page metafile payload and summary for a single page ID.',
    inputSchema: {
      additionalProperties: false,
      properties: {
        pageId: {
          type: 'string',
        },
      },
      required: ['pageId'],
      type: 'object',
    },
    name: 'get_page',
  },
  {
    description:
      'Return a component build metric by page ID and component name.',
    inputSchema: {
      additionalProperties: false,
      properties: {
        componentName: {
          type: 'string',
        },
        pageId: {
          type: 'string',
        },
      },
      required: ['pageId', 'componentName'],
      type: 'object',
    },
    name: 'get_component',
  },
  {
    description:
      'Return a shared prompt snapshot for a chunk or module artifact.',
    inputSchema: {
      additionalProperties: false,
      properties: {
        artifactKind: {
          enum: ['bundle-chunk', 'bundle-module'],
          type: 'string',
        },
        displayPath: {
          type: 'string',
        },
        file: {
          type: 'string',
        },
        moduleId: {
          type: 'string',
        },
      },
      required: ['artifactKind'],
      type: 'object',
    },
    name: 'get_artifact',
  },
  {
    description:
      'Return a saved build-time AI report payload by report ID or artifact key.',
    inputSchema: {
      additionalProperties: false,
      properties: {
        artifactKey: {
          type: 'string',
        },
        reportId: {
          type: 'string',
        },
      },
      type: 'object',
    },
    name: 'get_build_report',
  },
] as const satisfies {
  description: string;
  inputSchema: Record<string, unknown>;
  name: SiteDebugBuildMcpToolName;
}[];

const isRecord = (value: unknown): value is Record<string, unknown> =>
  Boolean(value && typeof value === 'object' && !Array.isArray(value));

const createJsonRpcErrorResponse = (
  id: JsonRpcId,
  code: number,
  message: string,
): JsonRpcResponse => ({
  error: {
    code,
    message,
  },
  id,
  jsonrpc: '2.0',
});

const createJsonRpcSuccessResponse = (
  id: JsonRpcId,
  result: unknown,
): JsonRpcResponse => ({
  id,
  jsonrpc: '2.0',
  result,
});

const serializeToolResult = (
  result: SiteDebugBuildMcpToolResult,
  isError = false,
) => ({
  content: [
    {
      text: JSON.stringify(result, null, 2),
      type: 'text',
    },
  ],
  ...(isError ? { isError: true } : {}),
  structuredContent: result,
});

const getRequiredString = (
  value: Record<string, unknown>,
  key: string,
): string => {
  const nextValue = value[key];

  if (typeof nextValue !== 'string' || nextValue.length === 0) {
    throw new Error(`"${key}" must be a non-empty string.`);
  }

  return nextValue;
};

const getOptionalString = (
  value: Record<string, unknown>,
  key: string,
): string | undefined => {
  const nextValue = value[key];

  if (nextValue === undefined) {
    return undefined;
  }

  if (typeof nextValue !== 'string' || nextValue.length === 0) {
    throw new Error(`"${key}" must be a non-empty string when provided.`);
  }

  return nextValue;
};

const createToolArgumentErrorResult = (message: string) =>
  serializeToolResult(
    {
      error: message,
    } as { error: string },
    true,
  );

const parseCliArgs = (argv: string[]): SiteDebugBuildDataOptions | null => {
  const nextOptions: SiteDebugBuildDataOptions = {
    outDir: '',
  };

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];

    if (argument === '--help') {
      return null;
    }

    if (argument === '--outDir') {
      nextOptions.outDir = argv[index + 1] || '';
      index += 1;
      continue;
    }

    if (argument === '--assetsDir') {
      nextOptions.assetsDir = argv[index + 1] || '';
      index += 1;
      continue;
    }

    throw new Error(`Unknown argument: ${argument}`);
  }

  if (!nextOptions.outDir) {
    throw new Error('Missing required argument: --outDir');
  }

  return nextOptions;
};

export interface SiteDebugBuildMcpServer {
  close: () => void;
  handleMessage: (message: unknown) => Promise<JsonRpcResponse | null>;
  listen: () => void;
}

export const createSiteDebugBuildMcpServer = (
  options: SiteDebugBuildMcpServerOptions,
): SiteDebugBuildMcpServer => {
  const dataStore = new SiteDebugBuildDataStore(options);
  const stdin = options.stdin || process.stdin;
  const stdout = options.stdout || process.stdout;
  const stderr = options.stderr || process.stderr;
  let buffer = Buffer.alloc(0);
  let closed = false;

  const writeMessage = (message: JsonRpcResponse) => {
    if (closed) {
      return;
    }

    const payload = Buffer.from(JSON.stringify(message), 'utf8');
    stdout.write(
      `Content-Length: ${payload.byteLength}\r\nContent-Type: application/json\r\n\r\n`,
    );
    stdout.write(payload);
  };

  const handleToolCall = async (
    name: SiteDebugBuildMcpToolName,
    args: unknown,
  ) => {
    const normalizedArgs = isRecord(args) ? args : {};

    try {
      switch (name) {
        case 'get_build_overview': {
          return serializeToolResult(dataStore.getBuildOverview());
        }
        case 'list_pages': {
          return serializeToolResult(dataStore.listPages());
        }
        case 'get_page': {
          return serializeToolResult(
            dataStore.getPage(getRequiredString(normalizedArgs, 'pageId')),
          );
        }
        case 'get_component': {
          return serializeToolResult(
            dataStore.getComponent(
              getRequiredString(normalizedArgs, 'pageId'),
              getRequiredString(normalizedArgs, 'componentName'),
            ),
          );
        }
        case 'get_artifact': {
          const artifactKind = getRequiredString(
            normalizedArgs,
            'artifactKind',
          );

          if (
            artifactKind !== 'bundle-chunk' &&
            artifactKind !== 'bundle-module'
          ) {
            throw new Error(
              '"artifactKind" must be "bundle-chunk" or "bundle-module".',
            );
          }

          return serializeToolResult(
            dataStore.getArtifact({
              artifactKind,
              displayPath: getOptionalString(normalizedArgs, 'displayPath'),
              file: getOptionalString(normalizedArgs, 'file'),
              moduleId: getOptionalString(normalizedArgs, 'moduleId'),
            }),
          );
        }
        case 'get_build_report': {
          const artifactKey = getOptionalString(normalizedArgs, 'artifactKey');
          const reportId = getOptionalString(normalizedArgs, 'reportId');

          if (!artifactKey && !reportId) {
            throw new Error(
              'Provide at least one of "reportId" or "artifactKey".',
            );
          }

          return serializeToolResult(
            dataStore.getBuildReport({
              artifactKey,
              reportId,
            }),
          );
        }
        default: {
          return createToolArgumentErrorResult(`Unsupported tool: ${name}`);
        }
      }
    } catch (error) {
      return createToolArgumentErrorResult(
        error instanceof Error ? error.message : 'Tool execution failed.',
      );
    }
  };

  const handleRequest = async (
    request: JsonRpcRequest,
  ): Promise<JsonRpcResponse | null> => {
    const id = request.id ?? null;

    switch (request.method) {
      case 'initialize': {
        return createJsonRpcSuccessResponse(id, {
          capabilities: {
            resources: {
              listChanged: false,
              subscribe: false,
            },
            tools: {
              listChanged: false,
            },
          },
          protocolVersion: PROTOCOL_VERSION,
          serverInfo: {
            name: SERVER_NAME,
            version: SERVER_VERSION,
          },
        });
      }
      case 'notifications/initialized': {
        return null;
      }
      case 'ping': {
        return createJsonRpcSuccessResponse(id, {});
      }
      case 'tools/list': {
        return createJsonRpcSuccessResponse(id, {
          tools: MCP_TOOLS,
        });
      }
      case 'tools/call': {
        const params = isRecord(request.params) ? request.params : {};
        const toolName = getRequiredString(params, 'name');
        const tool = MCP_TOOLS.find((item) => item.name === toolName);

        if (!tool) {
          return createJsonRpcSuccessResponse(
            id,
            createToolArgumentErrorResult(`Unknown tool: ${toolName}`),
          );
        }

        return createJsonRpcSuccessResponse(
          id,
          await handleToolCall(tool.name, params.arguments),
        );
      }
      case 'resources/list': {
        return createJsonRpcSuccessResponse(id, {
          resources: MCP_RESOURCES.map((resource) => ({
            description: resource.description,
            mimeType: resource.mimeType,
            name: resource.name,
            uri: resource.uri,
          })),
        });
      }
      case 'resources/read': {
        const params = isRecord(request.params) ? request.params : {};
        const resourceUri = getRequiredString(params, 'uri');
        const resource = MCP_RESOURCES.find((item) => item.uri === resourceUri);

        if (!resource) {
          return createJsonRpcErrorResponse(
            id,
            -32_602,
            `Unknown resource URI: ${resourceUri}`,
          );
        }

        return createJsonRpcSuccessResponse(id, {
          contents: [
            {
              mimeType: resource.mimeType,
              text: resource.text,
              uri: resource.uri,
            },
          ],
        });
      }
      case 'shutdown': {
        return createJsonRpcSuccessResponse(id, null);
      }
      case 'exit': {
        closed = true;
        return null;
      }
      default: {
        if (request.id === undefined) {
          return null;
        }

        return createJsonRpcErrorResponse(
          id,
          -32_601,
          `Method not found: ${request.method}`,
        );
      }
    }
  };

  const flushBuffer = async () => {
    while (true) {
      const headerEnd = buffer.indexOf('\r\n\r\n');

      if (headerEnd === -1) {
        return;
      }

      const headerText = buffer.slice(0, headerEnd).toString('utf8');
      const headers = Object.fromEntries(
        headerText
          .split('\r\n')
          .map((line) => line.split(/:\s*/, 2))
          .filter(
            (entry): entry is [string, string] =>
              entry.length === 2 &&
              typeof entry[0] === 'string' &&
              typeof entry[1] === 'string',
          )
          .map(([key, value]) => [key.toLowerCase(), value]),
      );
      const contentLength = Number.parseInt(headers['content-length'], 10);

      if (!Number.isFinite(contentLength) || contentLength < 0) {
        throw new Error('Missing or invalid Content-Length header.');
      }

      const messageStart = headerEnd + 4;
      const messageEnd = messageStart + contentLength;

      if (buffer.byteLength < messageEnd) {
        return;
      }

      const payload = buffer.slice(messageStart, messageEnd).toString('utf8');
      buffer = buffer.slice(messageEnd);

      const message = JSON.parse(payload) as JsonRpcRequest;
      const response = await handleRequest(message);

      if (response) {
        writeMessage(response);
      }
    }
  };

  let pendingFlush = Promise.resolve();

  return {
    close() {
      closed = true;
    },
    async handleMessage(message: unknown) {
      if (!isRecord(message) || typeof message.method !== 'string') {
        return createJsonRpcErrorResponse(null, -32_600, 'Invalid request.');
      }

      const normalizedMessage = message as unknown as JsonRpcRequest;

      try {
        return await handleRequest(normalizedMessage);
      } catch (error) {
        return createJsonRpcErrorResponse(
          normalizedMessage.id ?? null,
          -32_603,
          error instanceof Error ? error.message : 'Internal error.',
        );
      }
    },
    listen() {
      stdin.on('data', (chunk: Buffer | string) => {
        buffer = Buffer.concat([
          buffer,
          Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk),
        ]);
        pendingFlush = pendingFlush
          .then(() => flushBuffer())
          .catch((error) => {
            stderr.write(
              `${error instanceof Error ? error.message : 'MCP transport error.'}\n`,
            );
          });
      });
    },
  };
};

export const startSiteDebugBuildMcpServer = (
  options: SiteDebugBuildMcpServerOptions,
): SiteDebugBuildMcpServer => {
  const server = createSiteDebugBuildMcpServer(options);
  server.listen();
  return server;
};

export const runSiteDebugBuildMcpCli = async (
  argv: string[] = process.argv.slice(2),
): Promise<void> => {
  try {
    const options = parseCliArgs(argv);

    if (!options) {
      process.stdout.write(`${HELP_TEXT}\n`);
      return;
    }

    startSiteDebugBuildMcpServer(options);
  } catch (error) {
    process.stderr.write(
      `${error instanceof Error ? error.message : 'Failed to start MCP server.'}\n`,
    );
    process.stderr.write(`${HELP_TEXT}\n`);
    process.exitCode = 1;
  }
};

const currentFilePath = fileURLToPath(import.meta.url);

if (process.argv[1] && process.argv[1] === currentFilePath) {
  runSiteDebugBuildMcpCli().catch((error) => {
    process.stderr.write(
      `${error instanceof Error ? error.message : 'Failed to start MCP server.'}\n`,
    );
    process.exitCode = 1;
  });
}

export type {
  SiteDebugBuildArtifactSnapshot,
  SiteDebugBuildComponentSummary,
  SiteDebugBuildDataOptions,
  SiteDebugBuildOverview,
  SiteDebugBuildPageSummary,
  SiteDebugBuildReportPayload,
} from './react/site-debug-build-data';
