name: Lock Threads

on:
  schedule:
    - cron: 38 4 * * *
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock

jobs:
  action:
    if: github.repository == 'XiSenao/docs-islands'
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771
        with:
          issue-inactive-days: 7
          pr-inactive-days: 7
          exclude-any-issue-labels: "keep-open"
          exclude-any-pr-labels: "keep-open"
