name: Semantic Pull Request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    if: github.repository == 'XiSenao/docs-islands'
    runs-on: ubuntu-latest
    name: Semantic Pull Request
    permissions:
      pull-requests: read
    steps:
      - name: Validate PR title
        # amannn/action-semantic-pull-request@v6.1.1
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
